// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Desktop;
lv_obj_t * ui_DevNameLabel;
lv_obj_t * ui_TrueDevName;
lv_obj_t * ui_TitleLabel;
lv_obj_t * ui_TrueTitleLabel;
lv_obj_t * ui_ArtistLabel;
lv_obj_t * ui_TrueArtistLabel;
lv_obj_t * ui_AlbumLabel;
lv_obj_t * ui_TrueAlbumLabel;
lv_obj_t * ui_TimeLabel1;
lv_obj_t * ui_TimeLabel2;
lv_obj_t * ui_TrueTimeLabel;
lv_obj_t * ui_Spinner1;
void ui_event_PlayOrPauseBtn(lv_event_t * e);
lv_obj_t * ui_PlayOrPauseBtn;
void ui_event_PrevSongBtn(lv_event_t * e);
lv_obj_t * ui_PrevSongBtn;
void ui_event_NextSongBtn(lv_event_t * e);
lv_obj_t * ui_NextSongBtn;
void ui_event_VolumeSlider(lv_event_t * e);
lv_obj_t * ui_VolumeSlider;
lv_obj_t * ui_VolumeLabel;
lv_obj_t * ui_NextImage;
lv_obj_t * ui_PrevImage;
lv_obj_t * ui_PlayOrPauseImage;
lv_obj_t * ui_BluetoothImage;
void ui_event_ModeButton(lv_event_t * e);
lv_obj_t * ui_ModeButton;
lv_obj_t * ui_ModeLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_PlayOrPauseBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PlayOrPauseCallback(e);
    }
}
void ui_event_PrevSongBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PrevSongCallback(e);
    }
}
void ui_event_NextSongBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        NextSongCallback(e);
    }
}
void ui_event_VolumeSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        VolumeChangeCallback(e);
    }
}
void ui_event_ModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ModeChangeCallback(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
