// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Desktop;
extern lv_obj_t * ui_DevNameLabel;
extern lv_obj_t * ui_TrueDevName;
extern lv_obj_t * ui_TitleLabel;
extern lv_obj_t * ui_TrueTitleLabel;
extern lv_obj_t * ui_ArtistLabel;
extern lv_obj_t * ui_TrueArtistLabel;
extern lv_obj_t * ui_AlbumLabel;
extern lv_obj_t * ui_TrueAlbumLabel;
extern lv_obj_t * ui_TimeLabel1;
extern lv_obj_t * ui_TimeLabel2;
extern lv_obj_t * ui_TrueTimeLabel;
extern lv_obj_t * ui_Spinner1;
void ui_event_PlayOrPauseBtn(lv_event_t * e);
extern lv_obj_t * ui_PlayOrPauseBtn;
void ui_event_PrevSongBtn(lv_event_t * e);
extern lv_obj_t * ui_PrevSongBtn;
void ui_event_NextSongBtn(lv_event_t * e);
extern lv_obj_t * ui_NextSongBtn;
void ui_event_VolumeSlider(lv_event_t * e);
extern lv_obj_t * ui_VolumeSlider;
extern lv_obj_t * ui_VolumeLabel;
extern lv_obj_t * ui_NextImage;
extern lv_obj_t * ui_PrevImage;
extern lv_obj_t * ui_PlayOrPauseImage;
extern lv_obj_t * ui_BluetoothImage;
void ui_event_ModeButton(lv_event_t * e);
extern lv_obj_t * ui_ModeButton;
extern lv_obj_t * ui_ModeLabel;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_desktop_png);    // assets/desktop.png
LV_IMG_DECLARE(ui_img_next_png);    // assets/next.png
LV_IMG_DECLARE(ui_img_previous_png);    // assets/previous.png
LV_IMG_DECLARE(ui_img_play_and_pause_png);    // assets/play_and_pause.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/bluetooth.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
